# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(825, 608)
        self.centralWidget = QtWidgets.QWidget(mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setEnabled(True)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.powerHoursLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.powerHoursLayout.setContentsMargins(0, 0, 0, 0)
        self.powerHoursLayout.setObjectName("powerHoursLayout")
        self.powerHoursLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.powerHoursLabel.setFont(font)
        self.powerHoursLabel.setObjectName("powerHoursLabel")
        self.powerHoursLayout.addWidget(self.powerHoursLabel)
        self.powerHoursListView = PowerHourListView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerHoursListView.sizePolicy().hasHeightForWidth())
        self.powerHoursListView.setSizePolicy(sizePolicy)
        self.powerHoursListView.setMinimumSize(QtCore.QSize(0, 0))
        self.powerHoursListView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.powerHoursListView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.powerHoursListView.setObjectName("powerHoursListView")
        self.powerHoursLayout.addWidget(self.powerHoursListView)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.tracksLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.tracksLayout.setContentsMargins(0, 0, 0, 0)
        self.tracksLayout.setObjectName("tracksLayout")
        self.powerHourNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.powerHourNameLabel.setFont(font)
        self.powerHourNameLabel.setObjectName("powerHourNameLabel")
        self.tracksLayout.addWidget(self.powerHourNameLabel)
        self.tracklist = Tracklist(self.verticalLayoutWidget_2)
        self.tracklist.setMinimumSize(QtCore.QSize(0, 0))
        self.tracklist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tracklist.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tracklist.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tracklist.setDragEnabled(False)
        self.tracklist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tracklist.setShowGrid(True)
        self.tracklist.setObjectName("tracklist")
        self.tracklist.horizontalHeader().setStretchLastSection(True)
        self.tracksLayout.addWidget(self.tracklist)
        self.powerHourOptions = QtWidgets.QHBoxLayout()
        self.powerHourOptions.setObjectName("powerHourOptions")
        self.optionsSectionLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.optionsSectionLabel.setObjectName("optionsSectionLabel")
        self.powerHourOptions.addWidget(self.optionsSectionLabel)
        self.videoCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.videoCheckBox.setObjectName("videoCheckBox")
        self.powerHourOptions.addWidget(self.videoCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.powerHourOptions.addItem(spacerItem)
        self.tracksLayout.addLayout(self.powerHourOptions)
        self.createPowerHourButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.createPowerHourButton.setEnabled(False)
        self.createPowerHourButton.setObjectName("createPowerHourButton")
        self.tracksLayout.addWidget(self.createPowerHourButton)
        self.horizontalLayout_2.addWidget(self.splitter)
        mainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)
        self.actionShow_logs = QtWidgets.QAction(mainWindow)
        self.actionShow_logs.setObjectName("actionShow_logs")
        self.actionNew_Power_Hour = QtWidgets.QAction(mainWindow)
        self.actionNew_Power_Hour.setObjectName("actionNew_Power_Hour")
        self.action_Export_Current_Tracklist = QtWidgets.QAction(mainWindow)
        self.action_Export_Current_Tracklist.setObjectName("action_Export_Current_Tracklist")
        self.menuFile.addAction(self.actionNew_Power_Hour)
        self.menuFile.addAction(self.action_Export_Current_Tracklist)
        self.menuHelp.addAction(self.actionShow_logs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Power Hour Creator"))
        self.powerHoursLabel.setText(_translate("mainWindow", "Power Hours"))
        self.powerHourNameLabel.setText(_translate("mainWindow", "Name:"))
        self.optionsSectionLabel.setText(_translate("mainWindow", "Power Hour Options:"))
        self.videoCheckBox.setText(_translate("mainWindow", "Video?"))
        self.createPowerHourButton.setText(_translate("mainWindow", "Create Power Hour!"))
        self.menuFile.setTitle(_translate("mainWindow", "&File"))
        self.menuHelp.setTitle(_translate("mainWindow", "&Help"))
        self.actionShow_logs.setText(_translate("mainWindow", "Show logs"))
        self.actionNew_Power_Hour.setText(_translate("mainWindow", "&New Power Hour"))
        self.actionNew_Power_Hour.setShortcut(_translate("mainWindow", "Ctrl+N"))
        self.action_Export_Current_Tracklist.setText(_translate("mainWindow", "&Export Current Tracklist"))

from power_hour_creator.ui.power_hour_list import PowerHourListView
from power_hour_creator.ui.tracklist import Tracklist
